
CC 		= gcc
CFLAGS 		= -O3 -lrt -lpthread -I.
RM		= rm -f

default:
	$(CC) thread_period_simple.c -o thread_period_simple $(CFLAGS) 
	@echo '¡Compilación Terminada :D!'

clean:
	$(RM) thread_period_simple
	@echo '¡Borrando :(!'
